### ISSUE TITLE
How do you configure the extension to use a CMakeLists.txt file in a subdir?

### ISSUE THREAD

**Issue by rkeithhill** [vector-of-bool/vscode-cmake-tools#105]
Our primary CMakeLists.txt file is not in the root of our workspace but down in a directory named CMake.  As a result, when I open the workspace root folder, I don't see any of the CMake-Tools UI in the status bar.  I tried adding a workspace setting:
```
"cmake.sourceDirectory": "${workspaceRoot}/CMake"
```
But that didn't help.  Sorry for the n00b question.

**Comment by vector-of-bool** [comment]
That _should_ work. Do you see the CMake command line in the output window when you try to configure?

**Comment by rkeithhill** [comment]
OK good to know that it should work. Yes, I'm getting errors about an unknown CMake command "qt5_wrap_ui".  Some of the team is using Qt Creator to build.  Sigh..

**Comment by vector-of-bool** [comment]
Once you configure, do you see the CMake Tools UI in the status bar? It should appear after running one of the CMake Tools commands.

**Comment by rkeithhill** [comment]
Yes I do thanks!

**Comment by vector-of-bool** [comment]
Just to explain what's going on: VSCode lets extensions specify "Activation events," which will trigger when VSCode will load an extension (Extensions aren't loaded until one of the activation events occurs). In addition to all the extension's commands, I have an activation event for when a `CMakeLists.txt` file appears in the root of the project tree. Since your CMake files aren't in this location, the activation does not occur automatically.
