### ISSUE TITLE
Reduce warnings/pop-ups in new versions

### ISSUE THREAD

**Issue by nholthaus** [vector-of-bool/vscode-cmake-tools#110]
First off, I love CMake tools, and in my opinion it wouldn't really be possible to use visual studio code for C++ development without it.

One improvement that I think could be made is reducing the warning/pop-ups associated with the extension. They cover up the file tabs and are really annoying and overused by both code and many extensions. In general they make for a bad user experience.

For example, my team maintains a group of desktop machines which are reimaged occasionally, so every time we use a different machine or it gets updated, code _thinks_ that it is showing us the pop ups for the very first time, but in fact it's the millionth time. I know that some options are deprecated, and I know that there is debugger support now.

Trust that the users who actively care about trying out the new features are reading the release notes (especially now that they are integrated directly into code). If not, shame on them, but don't force pop-ups on all of us to try to catch a few disinterested users.

**Comment by vector-of-bool** [comment]
Thanks for the feedback! I'm thinking about adding some sort of telemetry so that I can actually gauge feature usage rather than throwing pop-ups and seeing what happens. I hadn't really considered your use case, but it makes sense that it would get troublesome. I'll remove the pop-ups next release. Until then, it is useful to note that all visible pop-ups/warnings can be dismissed with an escape key press.

Regarding deprecated options, though: I inserted those warnings as a way to ward off potential tickets or issues saying "Option X is suddenly broken." The deprecated option warnings should not appear unless you are actually making use of the bad options, and the options themselves should be completely non-functional. What is your use case that is causing them to appear?

**Comment by nholthaus** [comment]
There was a time when our maintainer thought it would be a good idea to enumerate every single option in the user settings, so probably it was actually being set when it shouldn't have been.

Didn't know about the `ESC` key press.

**Comment by vector-of-bool** [comment]
I was looking into reducing the number of pop-ups, and I found that the main offender, the "Debugging" popup, hasn't been in the code for a few versions. Could you identify what pop-up messages are causing you the most grief? I'll do my best to get them out of the way in the future.

**Comment by elalish** [comment]
I just noticed the reload this window to enable cmake-server warning, which I'm not using. Also, reloading the window just causes the message to appear again, so that seems more of a bug. Possibly related to 0.9.6 and 0.9.7 failing to allow anything to build. Had to downgrade to 0.9.4 and turn off auto updates to get back to a usable state.

**Comment by ytimenkov** [comment]
@elalish It is likely that you're using old CMake version. Please see #173 for workaround. I hope fixed version will be released soon.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
