### ISSUE TITLE
BUILD_SHARED_LIBS set to FALSE in InitializeCache.cmake

### ISSUE THREAD

**Issue by schwaerz** [vector-of-bool/vscode-cmake-tools#133]
I can't get our build working in vscode - although I'd really like too :smiley: 
I get some linker error and think this might be related to the following entry in ```build/CMakeTools/InitializeCache.cmake```
file:
```set(BUILD_SHARED_LIBS "FALSE" CACHE BOOL "Variable supplied by CMakeTools. Value is forced." FORCE)```

Didn't find an option to turn off this setting or to change it. Maybe I just didn't find the documentation.
Still strange to me why this is set at all.

Would be great if you could clarify so I can use this very nice plugin :smiley: productively.

**Comment by schwaerz** [comment]
Some further debugging confirmed by assumption.
This option breaks our build. Is it somehow possible to remove it?

**Comment by schwaerz** [comment]
Found a workaround. I need to configure the ```"linkage": "shared"``` inside ```cmake_variants```.
Still I feel this should be changed as this is some piece of duplicate code which could be avoided as the linkage is already defined in our CMakeLists.txt.

**Comment by vector-of-bool** [comment]
Sorry, I didn't really think about the fact that this was being set to false forcibly. CMake sets it to `FALSE` by default, and most users are unaware of its existence, so it hasn't really come up. I will probably look into having `linkage` be unset by default, then not setting `BUILD_SHARED_LIBS`, so that it doesn't trip up users that aren't asking for a specific linkage.

**Comment by schwaerz** [comment]
Thanks for looking into it. Would be great to have it unset by default.

**Comment by schwaerz** [comment]
:sunglasses:  That was really fast. Thanks for the great support, :smiley:
