### ISSUE TITLE
Is it possible to configure launch.js for calling cmake.build command as preLaunchTask?

### ISSUE THREAD

**Issue by magpier84** [vector-of-bool/vscode-cmake-tools#14]

**Comment by vector-of-bool** [comment]
Unfortunately, I don't believe you can. This would be a limitation of launch.json. You should be able to specify the name of a task from tasks.json, but even those are limited to only invoking external processes rather than VSCode commands. I would much prefer being able to invoke VSCode commands in task.json, that would enable greater integration with how VSCode handles running tasks.

**Comment by magpier84** [comment]
Thanks for reply. Strange limitation from VSCode :(
