### ISSUE TITLE
Missing CMake Server always wants to restart Code

### ISSUE THREAD

**Issue by norbertwenzel** [vector-of-bool/vscode-cmake-tools#173]
First thanks for your quick tips in #163/fix to the problems with CMake Server. I had disabled that explicitly for the last few days. After today's update to 0.9.7 I wanted to delete the explicit disabling of CMake Server from my settings. A popup appears that says I should restart VS Code to enable CMake Server. Even after restarting VS Code multiple times this message kept appearing. 
CMake actually worked as intended, but whenever I was compiling the message reappeared.

My system is Ubuntu Xenial with CMake 3.5.1 from the package manager. So if I'm not mistaken there should be no CMake Server installed.

Is this some issue with VS Code caching old settings or do I have to keep CMake Server disabled explicitly even after updating to 0.9.7?

**Comment by ytimenkov** [comment]
You may set `cmake.useCMakeServer` to false explicitly if this message annoys you or just ignore it (on this particular system).
Problem is that legacy implementation is not aware that it was activated because of fallback mechanism and not because configuration change, so it warns every time. Probably this warning should be just removed.

**Comment by norbertwenzel** [comment]
I've done that already, since the message annoys me. If it's safe to do so I'm fine with it. Thanks for your quick reply.

**Comment by vector-of-bool** [comment]
I'll reopen this because it's still not supposed to do this. Thanks for the report.
