### ISSUE TITLE
On Ninja, `clean` target fails due to `-j6`

### ISSUE THREAD

**Issue by neumannrf** [vector-of-bool/vscode-cmake-tools#18]
This issue is very similar to what was reported in [siegelaaron94/atom-build-cmake's issue 16](https://github.com/siegelaaron94/atom-build-cmake/issues/16).

Issuing **CMake: Clean** from the menu yields
```
[vscode] Executing cmake command: cmake --build ./build --target clean --config Debug -- -j 6
clean: invalid option -- 'j'
usage: ninja -t clean [options] [targets]

options:
  -g     also clean files marked as ninja generator output
  -r     interpret targets as a list of rules to clean instead
[vscode] CMake exited with status 1
```
Running the same command in the terminal without the offending `-- -j 6` option works just fine. It turns out **Ninja does not need** the `-j` flag, as it always compiles in parallel by default.

**Comment by vector-of-bool** [comment]
This is odd. I use Ninja on a daily basis and have never noticed CMake using the ``ninja -t clean`` tool rather than using the generated ``clean`` target. Nevertheless, I think I'll special case the ``clean`` target to not provide a ``-j`` argument. Even though Ninja will automatically perform parallelization, being able to specify a specify value for ``-j`` as a build option is important to some (See #17).

**Comment by neumannrf** [comment]
Everything looks fantastic after the upgrade! Thanks!
