### ISSUE TITLE
CMake settings per configuration type

### ISSUE THREAD

**Issue by dcourtois** [vector-of-bool/vscode-cmake-tools#195]
Hi, I was wondering if it would be possible to handle CMake settings (build folder, environments, options, etc.) on a per-configuration basis ?

Here is a small example of why I want this feature: I'm working with LLVM. The problem is when I need to debug the LLVM IR code generated: the debug version of `LLVM.so` is 700Mb ! It takes a lot of time to debug. So, I have 2 custom configurations for my project: `"Debug"` which is the usual debug type, but uses the system (release) version of LLVM, and a `"DebugLLVM"` configuration which uses a debug version of LLVM.

The problem is that I don't have any way of handling this by simply switching the current built type. It would be really handy if I could have a section somewhere (it can be in the cmake-variants.json file) where I can write something like this:

```
    "Debug": {
        "oneWordSummary$": "Debug",
        "description$": "Debug with LLVM in release",
        "buildType": "Debug",
        "cmake.buildDirectory": "${workspaceRoot}/build/debug"
    },
    "DebugLLVM": {
        "oneWordSummary$": "DebugLLVM",
        "description$": "Debug with LLVM in debug",
        "buildType": "DebugLLVM",
        "cmake.buildDirectory": "${workspaceRoot}/build/debug_llvm",
        "cmake.configureSettings": {
            "LLVM_DIR": "/my/path/to/llvm_debug"
        }
    },
```

Also being able to overwrite `buildDirectory` per configuration would be really helpfull since it would avoid re-generating things when switching build configuration, and would keep build trees independant.

**Comment by ytimenkov** [comment]
@dcourtois We're having this discussion in #190 and I'm trying to refactor the code to implement it.

At the moment, please try setting `cmake.buildDirectory` to something like `${workspaceRoot}/build/${buildType}` (in the settings). I'm not sure if CMake Tools will do rebuild or not when you change variants. I'm even less certain that Server Mode will handle such switch correctly (i.e. properly update metadata if you have different targets).

**Comment by dcourtois** [comment]
Ah sorry, didn't see it (well, saw it, but didn't read enough to understand that it was about the same things) sorry !

The build directory is really a "would be nice to have, but not that important" feature. The most important thing in my opinion is to be able to control cmake invocation on a per-configuration basis.

I'm going to close this issue and go read #190 in detail, thanks !

**Comment by dcourtois** [comment]
I'm reopening, sorry if for the flood ! I read #190 in detail, and I don't think these are related.
Maybe this proposal might help #190 but basically what you propose is to change the way the extension works to make more reliable, etc. whereas what I propose is just another optional set of configurations that would match the configuration types specified in `CMAKE_CONFIGURATION_TYPES`

I was writing about `cmake-variants.json` because currently it's the only way of specifying which build type we want. Ideally these would be retrieved from CMake directly (don't know if it's possible though) and then in a sort of `cmake_configurations.json` (or whatever the name) we could set CMake settings (build directory, CMake settings, environment, etc.) for each of those configuration.

**Comment by ytimenkov** [comment]
@dcourtois Determining `CMAKE_CONFIGURATION_TYPES` is not a rocket science when project is configured. Unfortunately it's a "chicken and egg problem": to configure it's necessary to know binary dir which comes from `CMAKE_CONFIGURATION_TYPES`.

Actually the snippet you gave is equivalent to what I wrote [in my comment](https://github.com/vector-of-bool/vscode-cmake-tools/issues/190#issuecomment-310781100).

Essentially CMakeTools should know which binary directories are (or should) exist and their properties: Generator, initial settings and active environment, allowing quick switching between them.

**Comment by dcourtois** [comment]
Hmm, I really have problems with how CMake works :D When reading the documentation (and judging from the name) `CMAKE_CONFIGURATION_TYPES` should be just a way of saying "hey guys ! I'm going to have the following configuration sets throughout my projects / targets / whatever !"

It's incredible that CMake is not able to just extract this information without having to configure first !
If I understand correctly, you have no way of querying the available configuration types ? So you need to configure once using one of the default 4 build type (even if the script explicitly removed them from `CMAKE_CONFIGURATION_TYPES`, which just seems crazy :/) and THEN you can query them and only then can you clean everything, and re-configure using one of the valid types provided by the script ??

Did I understand correctly ?

**Comment by ytimenkov** [comment]
@dcourtois Here comes long explanation :)

Major difference comes multi- (VS, probably XCode) and single- (Ninja, makefiles) configuration generators.

The former use `CMAKE_CONFIGURATION_TYPES` to populate configurations visible in IDE and then one of them is required in build command (or it falls back to default). `CMAKE_BUILD_TYPE` is ignored in this case. Also much of generator expression magic comes to make these multi-configuration generators work, because parameters for all configurations should be specified at once and then dynamically selected during build time.

Makefiles/Ninja on contrary ignore `CMAKE_CONFIGURATION_TYPES` and rely on `CMAKE_BUILD_TYPE`, so everything is specified and cached during configure time.

IIRC CMake doesn't do any consistency checks internally, so you may have missing or extra variables like `CMAKE_CXX_FLAGS_MYCONFIG`. So you need to define them properly only if you work with both VS and make.

Of course it is possible to simulate either approach: 
 1. Have multiple build directories preconfigured for makefiles (that's what I suggested to do by adding `${buildType}` to `cmake.buildDirectory`) to simulate VS behavior.
 1. Set `CMAKE_CONFIGURATION_TYPES` to just one value to force single configuration in VS, like in makefile. Then it is possible to initialize multiple directories like above.

In project I worked with we converged to the second approach, because we had much of cross-compilation. Also downloading library dependencies for all configurations was not feasible. so we had folders like `build/win32-debug`, `build/win64-release`, `build/android-internal` etc.

CMake Tools try to minimize this difference by providing variants, but in current implementation it uses same build directory and changing variant requires full rebuild. This doesn't scale for large projects.

**Comment by dcourtois** [comment]
Ok, I remember why I never used CMake for my personal projects now :D
A quick note on having 1 build folder per configuration: this is also what Qt Creator is doing

I didn't test using `${buildType}` in `cmake.buildDirectory`, but if it works, that's good: people have the choice to keep 1 single folder or one per build type.

The remaining problem (at least for me) is being able to specify options to use for each configuration.

**Comment by vector-of-bool** [comment]
Woops. I was completely absent for this discussion (which is somewhat important).

If I read correctly, you should already be able to do what you need using `cmake-variants.json`. A variant entry can contain a `settings` key, which corresponds to the `cmake.configureSettings` option. Is this insufficient for what you are trying to do?

**Comment by dcourtois** [comment]
Hi, I feel a bit stupid for not noticing the `settings` option in `cmake-variants.json` :/ I will need to check this when I have the time, but judging from your description, it's exactly what I'm needing !

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
