### ISSUE TITLE
Append or prepend default module path to CMAKE_MODULE_PATH instead of replacing it

### ISSUE THREAD

**Issue by Gagbo** [vector-of-bool/vscode-cmake-tools#208]
Currently, the module `InitializeCache.cmake` created by CMakeTools contains the line : 
`set(CMAKE_MODULE_PATH "c:/path/to/build/CMakeTools" CACHE STRING "Variable supplied by CMakeTools. Value is forced" FORCE)`

This prevents the use of `${CMAKE_MODULE_PATH}` in the rest of the project (a cmake subfolder under the root of the project in my case).

Noob questions incoming : 
- Is the "FORCE" really necessary ?
- Would the problem be solved if we just appended or prepended the former value (e.g. `set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "c:/path/to/build/CMakeTools" CACHE STRING "Variable supplied by CMakeTools. Value is forced" FORCE)` ) ?
- I suppose that InitializeCache.cmake is actually the first file to be read, so if the project we want to work on has to modify CMAKE_MODULE_PATH (say, first line of projectRoot/CMakeLists.txt), is this fix going to work ?

**Comment by vector-of-bool** [comment]
1. Yes, `FORCE` is requires for CMake Tools to manipulate those variables correctly.
2. N/A. There is no former value, since it is the first item to be loaded
3. Correct. The InitializeCache.cmake will never see a value for `CMAKE_MODULE_PATH`. The proper way to work with `CMAKE_MODULE_PATH` is to only ever use `APPEND`/`INSERT` on it:

```cmake
list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/cmake)
```

It is improper to overwrite it with a plain `set()` or a `set(CACHE)`. (This is okay in the `InitializeCache.cmake` file because the moment someone touches that variable, the cache value will be ignored.)

**Comment by Gagbo** [comment]
It actually works as intended when using `set(CACHE FORCE)` to append to the list
```cmake
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_CURRENT_LIST_DIR}/cmake" CACHE STRING "Modules for CMake" FORCE)
```

I don't know if it's the right way, but it seems logical to me and it works.

**Comment by vector-of-bool** [comment]
Does it work to `list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR}/cmake)`? That would be the most preferred option.

**Comment by Gagbo** [comment]
I tried but the cache didn't seem to update with the correct value, but it
may be due to a bad manipulation from me. I'll test again

Gerry AGBOBADA <http://fr.linkedin.com/in/gagbobada/en>
Ecole Polytechnique - Promotion 2010
+336 76 51 51 52
*gerry.agbobada@m4x.org <gerry.agbobada@m4x.org>*

2017-07-17 18:29 GMT+02:00 vector-of-bool <notifications@github.com>:

**Comment by ytimenkov** [comment]
@Gagbo 
> I tried but the cache didn't seem to update with the correct value, but it may be due to a bad manipulation from me. I'll test again

It should not. That's how CMake variables work:
 1. if you call `set()` w/o `CACHE` (as well as `list(APPEND ...)`), the value will be set, check with 'message()`.
 1. if you call `set(... CACHE)` without `FORCE` existing value won't be overwritten in the cache.

Why do you need to store the value in the cache?

In my practice this was only needed when we wanted to intercept CMake's initialization system in a non-intrusive way (kind of what `InitializeCache.cmake` does): initial CMake run was with `-DCMAKE_MODULE_PATH=xxx`, upon successive reconfigures the value taken from cache.

**Comment by vector-of-bool** [comment]
CMake will respect a locally `set()` `CMAKE_MODULE_PATH` over the cache version. `CMAKE_MODULE_PATH` shouldn't be set in the cache. (The `InitializeCache.cmake` uses `CACHE` because it is required for the vars to continue to the configure stage.)

After adding elements to the module path, `include()` and `find_package()` should work as expected.

**Comment by Gagbo** [comment]
I thought that the only way to check variables set in cache was to look in cache. I should have looked for the `message()` command.

`list APPEND` works as expected, thanks for the help :)
