### ISSUE TITLE
Failing to start debugging MSVC 14.0

### ISSUE THREAD

**Issue by BJMH** [vector-of-bool/vscode-cmake-tools#216]
Hey,

I'm running CMake Tools 0.10.2 on Windows 10 and using Visual C++ 2015 and 2017. In CMake Tools 0.10.1 and 0.10.2 I've had trouble starting debugging, getting the error: 

> Unable to start debugging. Launch options string provided by the project system is invalid. Unable to determine path to debugger. Please specify the "MIDebuggerPath" option.

Im able to start debugging with a launch.json, using:

```
{   
    "version": "0.2.0",  
    "configurations": [  
        {  
            "name": "Launch CMake-built program",  
            "type": "cppvsdbg",  
            "request": "launch",  
            "program": "${command:cmake.launchTargetProgramPath}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": true
        }
    ]
}
```

It appears to be related to line 895 in `common.ts`

`type: (this.compilerId && this.compilerId.includes('MSVC')) ? 'cppvsdbg' : 'cppdbg',`

For whatever reason `this.compilerId.includes('MSVC')` mustn't be returning true for MSVC 14.0. No idea why or how wide spread this is, because it worked on previous versions of CMake Tools where I was using 14.0. Though I have replicated this issue on two PCs. I can fix the problem for myself just by statically making the debugger `type: 'cppvsdbg'`.

Thanks

**Comment by dcourtois** [comment]
This is a C++ extension related problem, not a CMake Tools related one ...

And as for your problem, it's not a problem. On windows, you need to use `"cppvsdbg"` to debug things compiled with the Visual Studio compiler (`"cppvsdbg"` is just the option telling the C++ extension to use the Visual Studio debugger)

Using `gdb` or any other debugger with the MSVC compiler will obviously not work (I'm assuming that's what you were using since you get the `Please specify the "MIDebuggerPath" option` which is related to `gdb` debugger, if I remember correctly)

**Comment by BJMH** [comment]
I'm fairly certain its a CMake Tools problem, because it is line 895 in `common.ts` of the CMake Tools code that is erroneously returning `'cppdbg'` when it should be returning `'cppvsdbg'`. I am using MSVC, so `(this.compilerId && this.compilerId.includes('MSVC'))` should be `true` and therefore the type set to `'cppvsdbg'`.

The problem is happening when I use the CMake Tools debug button. Using the debug button provided by CMake Tools on the bottom bar there is no way for me to tell it to use `'cppvsdbg'`, as it is trying to determine that for me automatically and is getting it wrong.

The launch.json that I mentioned above is simply a work-around that uses the C++ extension to tell CMake Tools to start debugging with `'cppvsdbg'`, but nonetheless the CMake Tools debug button is currently failing to correctly determine the debugger on its own in a situation where it should.

**Comment by dcourtois** [comment]
Ok, the line number are mixed up, so I couldn't find what you were refering to, but I checked a bit more and now I see. Sorry for my previous answer that was a bit quick.

Also I didn't notice the problem because I'm using the default C++ extension `F5` debug command, not the CMake Tools one, which you are, and which obviously seems to be buggy :) When I have a few minutes to spare, I'll have a look.

In the meantime do you mind telling me why you are using the CMake debug command instead of the standard C++ extension one ? I've never used the CMake one, and I always provide a configured launch.json file with my project, so I'm curious to know about other people ways of doing things / workflow :)

**Comment by dcourtois** [comment]
Hmm, couldn't reproduce this on my computer. I debugged the CMake Tools extension to try and see where this could happen, and I couldn't find anything obviously wrong ...

Basically the line you pointed out is reading CMake cache, looking for the `CXX_COMPILER` entry, and then check the type of compiler to return `"MVSC"`, `"GNU"` or  `"Clange"`. So as long as the project is correctly configured and the cache file is not corrupted, it should work. Can you check in your build folder the content of `CMakeCache.txt`, and inside this file the content of the `CMAKE_CXX_COMPILER` entry ?

**Comment by BJMH** [comment]
Sorry, I was getting the line number from the installed extension on my PC. Here on GitHub the line is 978.

I looked in the CMakeCache.txt and it doesn't contain an entry for CMAKE_CXX_COMPILER. However, during generation I do get the output:
```
-- The C compiler identification is MSVC 19.10.25019.0
-- The CXX compiler identification is MSVC 19.10.25019.0
```
Even if I clear the Build directory and run is again with `set(CMAKE_CXX_COMPILER "MSVC 19.10.25019.0")`, that flag isnt appearing in CMakeCache.txt. I've also tried running the CMake gui and it doesn't add that to the cache file.

The only references I can find to MSVC in CMakeCache.txt is

```
CMAKE_GENERATOR:INTERNAL=Visual Studio 15 2017 Win64
CMAKE_LINKER:FILEPATH=G:/Programs/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX86/x64/link.exe
```

**Comment by dcourtois** [comment]
Which version of CMake are you using ?

**Comment by BJMH** [comment]
I've tried with three versions of CMake. 3.7.0-rc1, 3.7.2 and 3.9.0. I've also tried it on Windows and Mac for the same project.

On Windows, `CMAKE_CXX_COMPILER` never appeared in the CMakeCache.txt. On Mac, it only appeared for version 3.7.0-rc1.

I was able to make it appear on 3.9.0 on Windows if I used the CMake gui and chose `Specify native compilers` rather than `Use default native compilers` when selecting the generator and then gave it the path to cl.exe. Otherwise it doesn't appear.

**Comment by dcourtois** [comment]
Yay CMake ... (I'm forced to use it because of work, but those kind of weird behavior always remind me why I hate it in the first place :D)

Anyway back on topic, that's a pretty strange behavior we have here. I think it can be sorted out by checking the `CMAKE_LINKER` if `CMAKE_CXX_COMPILER` is not in the cache file. I don't know if I will have time to fix this, but even if I do, @vector-of-bool seems to be either on vacation or a bit busy at the moment, so my pull request would wait.

So in the meantime, you can either use the `launch.json` file or patch your `common.js` file locally, it shouldn't be difficult: locate the `compilerId` function in `client.js`, and edit it to look for `CMAKE_LINKER`, and check if it ends with `link.exe`.

**Comment by BJMH** [comment]
Yeah, CMake is definitely a love-hate relationship.

`CMAKE_LINKER` seems to always appear for me, so that might be a good sign. Also, if `CMAKE_CXX_COMPILER` isn't set and Visual Studio is the generator could you assume that MSVC is the compiler? I don't know if it's too large an assumption that if MSVC isn't the compiler when using VS then `CMAKE_CXX_COMPILER` would appear.

I've patched it for myself by hardcoding it to use `cppvsdbg`. The `launch.json` work-around is also fine, so a proper fix isn't too crucial if you're busy. Thanks for the help.

**Comment by dcourtois** [comment]
I don't really know. I know that in Visual Studio 2017 you can now use `clang`. But I don't know which debugging backend VS2017 is using in this case ... so my guess is that making assumption could work for most of users, but would fail for those of us with complicated setups.

But if `CMAKE_LINKER` is always there then it's good, because I'm pretty sure that the linker is what the tool want to check in order to decide on `cppvsdbg` or `cppdbg`. For instance you can compile with clang and link with msvc, and in this case, it's the vs debugger that's used. So always using `CMAKE_LINKER` seems more robust.

We'll just have to wait for the owner of CMake Tools to show around here to know what he thinks :) (I'll try to submit a pull request later today)

**Comment by vector-of-bool** [comment]
Here again. I'd bet it's because you're using the Visual Studio generator, and CMake doesn't need to know what compiler it will be using underneath that. As such, it never does that compiler check. Bleh. Those Visual Studio generators are the bane of my existence :D.

**Comment by dcourtois** [comment]
You might want to check the PR #218, it fixes this case for the server mode.

**Comment by Mischa-Alff** [comment]
I have this issue as well, @dcourtois' PR fixed it for me.

**Comment by Randshot** [comment]
**Closed**.
If this issues still persists in the current **_0.11.0-beta4_**, feel free to reopen this one or create a new one.
