### ISSUE TITLE
Configure / Generate run on every build

### ISSUE THREAD

**Issue by spinicist** [vector-of-bool/vscode-cmake-tools#239]
Hi,

If I run ```make -j``` on the command-line in my project directory, CMake will only do the ```configure/generate``` steps if a CMake file has changed. When I build within VSCode, these steps are run every-time.

What is the exact command issued by cmake-tools? Is there a way to disable this behaviour? It costs a non-trivial amount of time on my machine.

Thanks!

**Comment by vector-of-bool** [comment]
This is because of a bug in upstream CMake Server. It watches a set of files to do a dirty check, and fires a signal when any file changes to Mark the configuration as "out-of-date." Unfortunately, some of he files that it watches are written to by CMake itself, so it immediately fires the dirty signal after configuration is complete.

I just got an idea for a workaround on my part, but you can get around the problem by turning off CMake Server in your settings.json.

**Comment by spinicist** [comment]
Thanks - I've turned it off.

Through a combination of this and installing Ninja building is a good deal faster now. Interestingly, running the `install` target seems *much* faster with the CMake Server disabled!

I wouldn't worry about the workaround, this is fine for now so I'll close the issue. If & when it gets fixed by the CMake guys maybe you could add a note here?
