### ISSUE TITLE
missing double quotes (") around options -H -B -G passed to cmake

### ISSUE THREAD

**Issue by MinnieTheMoocher** [vector-of-bool/vscode-cmake-tools#27]
when you pass options to the cmake command line, e.g.

cmake -HD:\somefolder\myproject -BD:\somefolder\myproject\build -GVisual Studio 14 2015 -DCMAKE_BUILD_TYPE=Debug

, some of the options lack double quotes ("). They should be added
- to the -H option (to allow pathes with spaces in them)
- to the -B option (to allow pathes with spaces in them)
- to the -G option (just for readability)

, so you get

cmake -H "D:\somefolder\myproject" -B "D:\somefolder\myproject\build" -G "Visual Studio 14 2015" -DCMAKE_BUILD_TYPE=Debug

Without correcting this, spaces in folder names for
- source code
- build products
will not be buildable.

**Comment by vector-of-bool** [comment]
Uggh. I expected Node to be reasonable and automatically quote the arguments so that the Windows command parser will parse the ``args`` as a list of strings. It seems I'll have to manually do it myself. Thanks for letting me know.

**Comment by rtbo** [comment]
But why do you guys have spaces in your file trees!

OK troll apart, on linux I can use spaces and other special characters in `cmake.buildDirectory` without issue:
```[vscode] Executing cmake command: cmake -H/mnt/work/src/glfw-3.2 -B/mnt/work/src/glfw-3.2/répertoire de construction/Release -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DBUILD_TESTING=TRUE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=/mnt/work/src/glfw-3.2/répertoire d'installation/Release```

**Comment by vector-of-bool** [comment]
It probably works on Linux because [commands are invoked with a list of strings at the kernel level](http://pubs.opengroup.org/onlinepubs/9699919799/), but on Windows [processes are invoked with a single string, which they must parse on their own](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425(v=vs.85).aspx). (Usually the CRT will parse the command line and pass the separated strings to ``main()``). I assumed Node would do the quoting properly, but it absolutely doesn't. There are a few open issues in Node related to this. Needing to do the quoting complicates things considerably, as we also need to properly handle quotes in the commands as well. :disappointed:

**Comment by vector-of-bool** [comment]
Hmm... @MinnieTheMoocher is this actually causing an issue on your system? On my Windows system, strings with spaces are passed correctly to CMake

**Comment by MinnieTheMoocher** [comment]
> But why do you guys have spaces in your file trees!
Sorry, but "space" is a completely valid element in file names,
and existing projects cannot be changed so easily.
If that is a valid character, all tools need to properly support it.
<end of reply to rant>
__________________________________

I will re-check if the missing quotes really produce a problem.
I asked for the quotes because we currently have them present in all our projects,
and I immediately noticed that they were missing in the cmake command line constructed by VS Code.
If I remember correctly, we explicitly had added the quotes due to problems on either Windows or Linux. As said, I have to re-check.
Besides that, adding them shouldn't hurt, so maybe just adding them could shortcut the discussion here.

**Comment by vector-of-bool** [comment]
Adding them might actually hurt, because Node may be passing the strings verbatim, which would result in the quotations actually being passed to CMake, rather than parsed by the shell beforehand.

I think (and correct me if I'm wrong) that you are referring to the ``[vscode] Executing CMake command: cmake ...`` which is shown in the CMake/Build output within Code itself. In that situation, that is simply using ``Array.join(' ')`` to render something useful for the user to see, but the command is being passed properly as an array of strings. Nevertheless, I might as well quote the strings in the output window to make it clear that the command will be run properly.

**Comment by MinnieTheMoocher** [comment]
ah, I understand. yes, I was referring to that log line.
I was looking at it and not seeing the quotes I knew from being present in our existing
build scripts.
However, please let me anyway double check if really everything works right right now.
I will come back here.
