### ISSUE TITLE
suggestion: use a different default for build and install output folder

### ISSUE THREAD

**Issue by MinnieTheMoocher** [vector-of-bool/vscode-cmake-tools#32]
In version 0.4.0, the current default value for the build results folder is:
`"cmake.buildDirectory": "${workspaceRoot}/build"`
, and for the install results folder is:
`"cmake.installPrefix": null`

I would like to suggest to change that to
`"cmake.buildDirectory": "${workspaceRoot}-build-${buildType}"`
`"cmake.installPrefix": "${workspaceRoot}-install-${buildType}"`
for 2 reasons:

(a) BUILD: Putting build results *into* the source code tree is a Bad Thing (TM). People doing so have to explicitly ignore that folder in their revision control tool (e.g. git). It is better to completely separate the build results from the input code. If somebody REALLY wants to put the build results INSIDE the source code, he/she can still do so by explicitly setting that folder in his/her user settings or workspace settings.

(b) INSTALL: Usually you will not want to "contaminate" your build machine with installation results.
The current default of "null" has that effect, i.e., when building "INSTALL", e.g. the "bin" folder of your building host machine gets filled with that build result. What you normally want is to get all the build results into a dedicated "install" folder (as suggested above), and then do more things with that,
for example create an installation package from that using e.g. CPack. After that, the installation package usually gets tested on a dedicated installation test machine, which applies that resulting package and checks if the installation works properly. You will usually not want that on your build host.

**Comment by vector-of-bool** [comment]
This is a contentious one.

It's pretty well agreed that polluting the source tree with build artifacts is generally awful (Autotools 😠!), but less so on where to put them. I personally like putting them in a ``build`` subdirectory of the source tree and just adding it to ``.gitignore``, and I've seen it used as a common CMake idiom of:

~~~bash
git clone blah
cd blah
mkdir build
cd build
cmake ..
~~~

which is where I got it from initially.

I'm aware that there is another convention to use ``<project-name>-build`` as the build directory, as is the default with some tools (like QtCreator).

In this case, I'm strongly inclined to leave it with the current default, as it keeps everything within ``${workspaceRoot}``. This means that I don't suddenly start creating files in some place the user can't immediately see (the effects are constrained to the current workspace). It also means that the build directory can easily be browsed within VSCode to see build artifacts.

As for ``install``... I'm really not sure. Note that the default install prefix (on *nix systems) is ``/usr/local``, not ``/usr``. ``/usr/local`` is specifically designed for containing things like locally-build binaries, so I don't really consider it to be polluting the system. Also note that CPack (when used via ``include(CPack)``) expects something like ``/usr`` or ``/usr/local`` for the install prefix, and uses the ``DESTDIR`` mechanism to control the temporary packaging root.

I guess it really boils down to what the most users prefer. I won't dictate something just because it happens to be convenient in my workflow.

**Comment by MinnieTheMoocher** [comment]
I completely agree with you.
I also can change the defaults you chose in my user settings, so technically everything is fine right now.
Also, changing the current defaults would maybe bother you users.
I just wanted to drop this change request here, as for the projects I work in,
an installation into the build host never is a usecase, and should we switch to using VSCode,
then we will have to instruct all users to set proper user default settings (which we anyway will
need to do probably, so it doesn't really hurt).

I was just wondering if this could also be the case for more users than just me/us.

One more thought on the "build" folder:
Qt recently has changed their folder naming and now puts also the destination platform etc. into that folder name. There is also the usecase that you want to build your source for both Debug and Release and do not want to throw away your build results each time you switch. And, you might want to use different generators in parallel. All this leads to a more "speaking" build results folder name
instead of just "build", for example:
myproject-build-vs14-debug
myproject-build-vs14-release
myproject-build-vs10-debug
myproject-build-vs10-release
and so on (taking VS14 and VS10 as examples here)

**Comment by vector-of-bool** [comment]
Due to lack of feedback, I'm going to close this issue.
