### ISSUE TITLE
Create build directory only if build is performed

### ISSUE THREAD

**Issue by mloskot** [vector-of-bool/vscode-cmake-tools#379]
### Brief Issue Summary

The `build` directory should NOT be (re)created every time user opens a folder with `CMakeLists.txt` in VSCode, but only on-demand when actual build is configured/performed.

### Expected:

1. `mkdir test`
2. Create `test/CMakeListst.txt`
```
cmake_minimum_required(VERSION 3.10 FATAL_ERROR)
project(test)
```
3. Explore(r) to parent of `test` > right-click on `test` > Open with Code
4. Close the Code
5. No `test/build` subdirectory should be created and left dangling as empty cruft!

### Apparent Behavior:

5. `test/build` subdirectory is created, despite it is EMPTY and has NOT been used.

[[For issues, fill out the following. Otherwise delete this section.]]

- **Operating System**: Windows 10 Version 1709 (Build 16299)
- **CMake Version**: 3.11
- **VSCode Version**: 1.22.1
- **CMake Tools Extension Version**: 0.10.4

**Comment by KoeMai** [comment]
Do I understand it right. You want only the build directory if you trigger build of the project. But you want to see the possible targets in the status bar so that you chould build when you start working on the project?

The build folder depends on configure cmake and is needed to get the targets for the UI. I am not sure how the extension should know that the user likes to view only the source code or he like to work on source code.

What is your use case?

**Comment by vector-of-bool** [comment]
@mloskot I think this might have been implemented accidentally as part of an extension startup refactor. Do you still see this occurring in the 1.0.0 release?

**Comment by vector-of-bool** [comment]
I'm going to close this, but re-open it if it is still occurring.

**Comment by mloskot** [comment]
@vector-of-bool using the latest VSCode 1.25.0-insider with the CMake Tools 1.0.1 I no longer see the problem occurring. Thank you!
