### ISSUE TITLE
Newbie Guide

### ISSUE THREAD

**Issue by spinicist** [vector-of-bool/vscode-cmake-tools#5]
Hello, I am trying out VSCode as an editor for my C++/CMake project. Thank you so much for building this plug-in, it looks really promising for my needs.

I would really like to build a specific target (install) for my project with a keyboard shortcut, or bind the 'CMake: Build Target' command to a keyboard shortcut. Could you provide some details for how to do this, or which source code files I should look in? I am failing at the step of what to write in my settings.json file, or what command to use in my keybindings.json file.

**Comment by vector-of-bool** [comment]
Thanks for the feedback.

The ``CMake: Build Target`` command is named ``cmake.buildWithTarget``, thus the following ``keybindings.json`` entry should bind that key:

~~~json
{
    "key": "shift+f7",
    "command": "cmake.buildWithTarget"
}
~~~

Of course you can use whatever key combination you like.

At the moment, the default build command always builds the ``all`` target, but I'm planning on adding a way to change the target that will be invoked with the build command, whether that be an entry in ``settings.json`` or some per-session variable.

Since ``install`` is a common target to use, I may just add another command that invokes the install target.

I'll eventually update the ``README.md`` with more details about what the extension can do.

As a side note, all commands available for binding (including the ``cmake.*`` ones) are listed in the _Default Keyboard Shortcuts_ view as a lengthy comment toward the bottom of the file.

**Comment by spinicist** [comment]
Brilliant, thanks for the speedy reply. I hadn't noticed the cmake commands were at the bottom of keybindings.json file.

One more thing - is there a way to automatically clear the output panel before building? I can't see any keybinding that sounds likely. The only way seems to be to actually click the 'Clear Output' button.

**Comment by vector-of-bool** [comment]
At the moment, no. But I am planning on adding a "Clear output before build" setting that can be enabled.

**Comment by spinicist** [comment]
Great, I'm looking forward to it. I'll close this Issue now - do you want another one titled "Clear output before build" that can be marked as an Enhancement request?

**Comment by vector-of-bool** [comment]
Sure, that would be helpful. Thanks!
