### ISSUE TITLE
Allow invoking cmake from a specific shell

### ISSUE THREAD

**Issue by MB3hel** [vector-of-bool/vscode-cmake-tools#521]
### Brief Issue Summary
Sometimes it is necessary to run cmake from a different (non cmd) shell on windows. For example when using MSYS2 to install libraries (eg wxWidgets) using pacman it is necessary to run cmake from MSYS2's sh.exe or it will be unable to find the libraries installed with pacman. Would it be possible to add a setting to allow running cmake from a specific shell on different oses?

Possibly something like
`cmake.shell.win = "C:\msys64\mingw64shell.bat"`

**Comment by vector-of-bool** [comment]
Sorry for the delay.

Trouble is that CMake isn't really executed by _any_ shell. It is started via Node's `child_process`, which I believe simply wraps `CreateProcess()`. It's more likely that it needs some set of environment variables from MSYS, and to run the correct `cmake.exe` installed in MSYS. What happens if you try to set `cmake.cmakePath` to the binary installed by `pacman` inside of `C:\msys64`?

I've not used MSYS or pacman on Windows, so I wouldn't know quite how to start looking into this one, nor how to write tests to validate it.

**Comment by MB3hel** [comment]
Ok, I have a solution. Putting MSYS2's sh.exe in the system's PATH allows the use of CMake's MSYS Makefiles generator which finds the libraries correctly. It seems like this is the easy way to deal with this as CMake will find and use sh.

**Comment by tan-wei** [comment]
@MB3hel Change `PATH` maybe a choice. However, if I do not want change `PATH` in the system, can we just change `PATH` in VS Code? Maybe create a bat file to launch VS Code can be a solution. But it is not that elegant. Is there any method such as changing `settings.json` to add something in `PATH` just for a specific project alone? Thanks!

**Comment by MB3hel** [comment]
You should be able to add something like this to your settings.json if you just need the path set for cmake @tan-wei

```
"cmake.environment": {
    "PATH": "C:/MSYS/bin;${env:PATH}"
},
```
