### ISSUE TITLE
debugConfig documentation

### ISSUE THREAD

**Issue by amigo421** [vector-of-bool/vscode-cmake-tools#53]
I see there was a discussion about that in a some request below,
hope this is okay for you that I've raised this request separately

the default template looks like

> "cmake.debugConfig": {
>         "all": {
>             "request": "launch",
>             "cwd": "${workspaceRoot}",
>             "linux": {
>                 "MIMode": "gdb"
>             },
>             "osx": {
>                 "MIMode": "lldb"
>             },
>             "windows": {
>                 "MIMode": "gdb"
>             }
>         }
>     }

it doesn't look enough clear.
1. Are the tags above the only available settings or just basic ones? exist other ones? please describe
2. can these [cpptools settings](https://github.com/Microsoft/vscode-cpptools/blob/master/launch.md) can be also used ?
3. please provide a couple samples, firstly with a most useable case: run with a command line arguments

**Comment by vector-of-bool** [comment]
These debug options are forwarded to the cpptools debugger, so you can use any options for that debugger in this config option. I need to fill out the option schema properly so that it can help users fill out their settings. The target debugging feature still has some work to do, and with the new cmake-server support coming, it may become a lot more stable soon. The documentation definitely needs to be updated.

**Comment by vector-of-bool** [comment]
In the latest release, I've filled out a better schema for `debugConfig`. Now VSCode should help you fill it out. Take a look at the docs for some more details. If you feel like the docs are sufficient, please close this issue, otherwise feel free to ask any more questions. Thanks!
