### ISSUE TITLE
Providing the wrong lldb path for the cpptools extension

### ISSUE THREAD

**Issue by pieandcakes** [vector-of-bool/vscode-cmake-tools#584]
I am one of the authors of the Microsoft cpptools extension. We are getting people complaining about using the wrong default lldb when also using this extension. @joole reported that overwriting `cmake.debugConfig` and specifying the `miDebuggerPath` is working, but setting the `miDebuggerPath` in the `launch.json` does not.

It seems like this extension is overwriting the debug settings. I would say for [this](https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/src/debugger.ts#L80) line, we use `lldb-mi` and not the regular version of `lldb`. This should be updated to either find the corresponding `lldb-mi` OR use the default one in the extension. We do that by default when the user doesn't specify the `miDebuggerPath` but because you are specifying it, it is breaking debugging on MacOS.

**Comment by pieandcakes** [comment]
After investigating more, this only happens with `Run with debugger` in the CMake pane, which is then giving you the option to Open the `launch.json` which will show the correct info. I don't know what the right fix for that would be but it might be better to save your debug settings to the `launch.json` file so that it is more transparent to the user.

**Comment by pieandcakes** [comment]
Related to: https://github.com/Microsoft/vscode-cpptools/issues/2456

**Comment by vector-of-bool** [comment]
Hello! Sorry for the delay. I've been busy with a few things.

Sorry to inundate you with noisy false-positives.

To fix the LLDB issue, it should just be a matter of changing the search for `lldb` to `lldb-mi`.

The reason that setting `miDebuggerPath` in `launch.json` _appears_ to not work is that (as you have discovered) they run the extra debug command that CMake Tools provides, which side-steps `launch.json` and directly calls the VSCode command API to launch the debugger with an on-the-fly generated debug configuration. It seems that VSCode/cpptools detects the faulty config and the "edit config in `launch.json`" isn't applicable since the config didn't come from `launch.json` to begin with.

The "Run with debugger" command is something users find nice since they don't even need the `launch.json` to work with it, but it's been giving hiccups since I first added it. It should be made very clear that the "Debugging" that CMake Tools provides is disjoint from `launch.json`. I've seen a lot of confusion in this regard.

Again, I apologize that you had to deal with this. I try my best to make the documentation as visible as I can, but it just sometimes doesn't work out.

I think I'll add a pop-up that directs people to the documentation in the first time that they run a CMake target-debug and also have a `launch.json` present. That will at least help inform users of the nuance involved.

**Comment by vector-of-bool** [comment]
I've tweaks the path to the debugger file in [this commit](https://github.com/vector-of-bool/vscode-cmake-tools/commit/4f03d9961fd8fe9f55290d57e75dd534d163fc83). Does that look correct?

**Comment by pieandcakes** [comment]
@vector-of-bool That looks good to me.

I think the problem stems from when we get the incorrect information, we return a debug result of "failed" during the launch command, VS Code knows its probably an issue with launch.json which is where that button comes from.
