### ISSUE TITLE
Multiple configurations?

### ISSUE THREAD

**Issue by dattrax** [vector-of-bool/vscode-cmake-tools#66]
I'm new to vscode/cmake-tools.  I've a project which uses a different toolset/config options depending on whether I cross compile or not.

settings.json has my cmake.configureSettings, and this is working fine for x86.  Is there a way to add a 2nd configure in to support another build directory and architecture?

**Comment by vector-of-bool** [comment]
Sorry for the late reply. You might want to look at the [ ](https://github.com/vector-of-bool/vscode-cmake-tools/blob/develop/docs/build_variants.md) eature I added a while ago.

**Comment by vector-of-bool** [comment]
Sorry, I'm on mobile and it seems to have garbled my last comment.

You may want to look at the "build variants" feature I added a while ago. You can find docs for it in the docs subdirectory of the repo. It doesn't let you configure *every* feature of the build (yet), but it may suffice for your usages?

Tell me if there are any features you'd like to see added to cmake-variants.json in order to support your use case.

**Comment by vector-of-bool** [comment]
@dattrax, does the Build Variants feature help solve your issues?

**Comment by vector-of-bool** [comment]
Do to lack of activity, I am inclined to close this issue. Please respond if you would like to continue this discussion. Otherwise, I will close this issue by the end of today.
