### ISSUE TITLE
CMakeToolsHelpers breaking VS builds

### ISSUE THREAD

**Issue by nsubtil** [vector-of-bool/vscode-cmake-tools#73]
Including CMakeToolsHelpers seems to break VS builds:

CMake Error in CMakeLists.txt:
  Evaluation file to be written multiple times for different configurations
  or languages with different content:

    build/CMakeToolsMeta.txt

This has been cropping up every now and then. It's hard to say what triggers it. Sadly, target debugging won't work without this.

**Comment by vector-of-bool** [comment]
The `CMakeToolsHelpers` script has been proving to be problematic. It is a way to get information out of CMake that it hasn't in the past been very willing to give up. With CMake 3.7 and `cmake-server`, I'll be able to finally ditch the helper script, so that's the good news. The bad news is that `cmake-server` support is still in progress for now and will require some CMake bugfixes, and not everyone will be upgrading to CMake 3.7 immediately, so we're stuck with it for now.

Could I see the contents of `CMakeToolsHelpers.cmake` that you have in your build directory when this occurs? Also, are you able to determine under what circumstances the error message appears?
