### ISSUE TITLE
Move CMakeTools to be an Extra Generator

### ISSUE THREAD

**Issue by danme** [vector-of-bool/vscode-cmake-tools#77]
I don't know if this is feasible but to remove the need to include(CMakeToolsHelpers OPTIONAL) can we contribute an Extra Generator to CMake itself? This would be nice to keep the impact of the used Editor/IDE as minimal as possible in the source dir.

So we call `cmake -G "VSCode CMakeTools - Ninja" ../src` to generate the needed metadata?

**Comment by vector-of-bool** [comment]
It's doubtful, but it would be useful. Adding an extra generator would need to modify the upstream CMake code itself and would require a new version of CMake.

But there's good news: As of CMake 3.7, there is `cmake-server` from which a tool can pull the required build information. I'm currently working on this in a branch and, once it is finished, the `CMakeToolsHelpers` script will no longer be necessary. It will also open up even more opportunities for build system integration.

Unfortunately, in the course of working on `cmake-server` support, I've discovered a few crashing CMake bugs related to the feature, but I've been submitting bug reports and we should see some fixes in CMake 3.7.1.

So the answer is: Not yet, but stay tuned!

**Comment by vector-of-bool** [comment]
Boo: More CMake bugs are still preventing me from releasing the CMake Server support I'm wanting. I've got the whole thing ready and literally have the branch to activate it commented out in the current release. The problem is that if I release it in it's current form, too many users will immediately run into some latent CMake Server issues. Thanks for the patience, but I promise that I haven't forgotten about this. Keep an eye on extension releases for the CMake Server support: it's getting close. Maybe CMake 3.8.0?
