### ISSUE TITLE
any chance to add MinGW auto-detection (in addition to VC family)?

### ISSUE THREAD

**Issue by amigo421** [vector-of-bool/vscode-cmake-tools#89]

**Comment by amigo421** [comment]
by the way: when I'm trying to configure for MinGW generator:

` "cmake.configureArgs": [
        "-G \"CodeBlocks - MinGW Makefiles\""
    ]
`

I have this problem : 

> cmake -Hc:/dev/workspace/algolist -Bc:/dev/workspace/algolist/build -Cc:\dev\workspace\algolist\build\CMakeTools\InitializeCache.cmake -DCMAKE_BUILD_TYPE=Debug "-G "CodeBlocks - MinGW Makefiles""

you see this passes the parameter without cutting off the quotes. do you know how to avoid this ?

**Comment by vector-of-bool** [comment]
`configureArgs` passes each string in array as a separate argument, so it quotes that string to pass it all as one argument.

Instead of passing it in with `configureArgs`, set `cmake.preferredGenerators` or `cmake.generator`. Prefer using the dedicated configuration options to passing arbitrary values to `cmake.configureArgs` or `cmake.buildArgs`

**Comment by vector-of-bool** [comment]
Building a MinGW environment is definitely possible. The tricky part is figuring out where it is installed. There are a few common paths I'd be able to search, but I can't be guaranteed to get them all. I'll see what I can do.

**Comment by amigo421** [comment]
unlike vc toolchain. mingw has pre-defined and stable folders structure, so if you have a root of mingw or bin subfolder path, you can find (and set) all required paths to libs and headers, is not it? also mingw (unlike vc) doesn't use registry , so from my perspective, the search in %PATH% would be enough, cmake.xxx setting with a path to mingw root would be also okay....

thank you for the comment about generator!

**Comment by vector-of-bool** [comment]
I'm about to start some large refactoring for new cmake-server support. As such, it may be a few days before I can address this. The code is in need of some cleanup and simplification. I've got a somewhat thorough test suite, so it shouldn't take too long. Thank you for the suggestion!

**Comment by JamesYeoman** [comment]
@vector-of-bool Any news on the progress on this? I am struggling to get CMake to know that I don't want to use VC. I much prefer MinGW so...

**Comment by vector-of-bool** [comment]
Sorry that I haven't been as active for a while. I haven't forgotten this project, I promise!

The next release will have experimental support for `cmake-server`. All of my work on the feature is done, but there is an upstream bug in CMake 3.7.1 that will be fixed in 3.7.2 that renders `cmake-server` somewhat unusable. Rather than release with a completely broken (even if experimental) feature, I'm going to wait until 3.7.2 so that people can at least try the `cmake-server` support and I can get some feedback on it.

The reason progress seems to have stagnated is that I prematurely merged the branch I was doing this work on before I discovered the upstream CMake bug. It would be a non-trivial task to undo the changes or work around it, so I'm putting the next release on hold for a while. Some considerable refactoring went into this branch, and there are several other bugs and features I'd like to get addressed, but I want to get the large refactor changes out before I try adding any new features.

**Comment by vector-of-bool** [comment]
Wow, to "sorry for inactivity" messages in a row. That's pretty bad.

The holidays and new year have kept me busy. I'm sorry again for having this sit around. I think it's about time I start using the _Milestones_ feature, so I've added one for this issue and given it a deadline of next week. Fingers crossed that I can get it done!

**Comment by vector-of-bool** [comment]
Should be out in next release

**Comment by vector-of-bool** [comment]
Should be available now. If you have any feedback, just comment on the issue. Thanks!
