### ISSUE TITLE
targetDebug for a libraries

### ISSUE THREAD

**Issue by amigo421** [vector-of-bool/vscode-cmake-tools#97]
just one more question please:
so I've created sample nodejs native addon in vscode using your extension
 (based on cmake-js instead of node-gyp)
that was built and ran successfully, but I need to debug this , so two questions are there
1. even I 've included support cmake script as usual, anyway I don't see that toolbar item for the debug. does it mean that debugging support is an application for only? not for a libraries?
2. could you provide us with a sample how to start a debugging a libraries loaded by some host aplciation? (nodejs in my case)

thank you
![img-2016-12-15-19-27-06](https://cloud.githubusercontent.com/assets/3259933/21232392/7ca66d0e-c2fc-11e6-854a-410b53fdff0c.png)

**Comment by vector-of-bool** [comment]
That's tricky... You cannot debug a library directly since it has no "entry" point akin to an executables `main()` function. You would need to create an executable which loaded the library, then you could debug it from there. It may be possible if you define an executable in your CMakeLists.txt which loaded up the library and called into the functionality that you wish to debug.

If you wish to debug the library in the context of a NodeJS runtime-loaded extension, then you'd need to create a debug config that launched NodeJS in such a way that it loads up the extension and makes use of it somehow.

**Comment by amigo421** [comment]
Thank you for detailed explanation, and sorry for unclear question. Actually I have a lot of debugging experience, but unfortunately not for cmake based project. Thank you that paid my attention that there are cmake options for this. I'll look for this

**Comment by vector-of-bool** [comment]
Sorry to have disappeared for so long. I've been busy with "real life" for a while, so I haven't been able to get back to working on this project as quickly as I wanted to.

Were you able to solve your problems? Are there any follow-up questions you have? If not, could I close this question?

**Comment by amigo421** [comment]
Yes, thank you, please close the ticket

**Comment by vector-of-bool** [comment]
Thanks for the interest in the project!
